//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AI_Lib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int user_id { get; set; }
        public string user_login { get; set; }
        public string user_password { get; set; }
        public Nullable<int> user_book_limit { get; set; }
        public string user_name { get; set; }
        public string user_first_name { get; set; }
        public string user_email { get; set; }
        public Nullable<System.DateTime> user_rergistration_date { get; set; }
    }
}
